# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3-10-g1536ecf
_src_path: git@git.sr.ht:~dmerej/copier-python
author_email: dimitri@dmerej.info
author_name: Dimitri Merejkowsky
package_import_name: team_maker
project_description: Create teams based on a list of names
project_name: team_maker
project_version: 0.0.1

